arduino_cli_path : /home/pi/arduino_cli/bin/arduino-cli 
arduino_build_directory : /home/pi/arduino_build
arduino_core_build_directory : /home/pi/arduino_build_core
example_search_directory : /home/pi/ch55xduino/ch55xduino/ch55x/libraries/Generic_Examples/examples
error_log_file : /home/pi/ch559jigPython/arduino_example_build_error.log
batch_build_directory : /home/pi/batch_build
upload_tool_path : /home/pi/.arduino15/packages/CH55xDuino/tools/MCS51Tools/2023.04.23/linux/vnproch55x
test_script_directory : /home/pi/ch559jigPython/sketchTestCode
